In [2]:
import urllib
import urllib2
from datetime import timedelta, date
from bs4 import BeautifulSoup as bs
from pandas import DataFrame as df
import sys
import os
import time
import performance as p

In [56]:
def range_switcher(x):
    if 5<x<=10:
        return '6-10'
    elif 10<x<=15:
        return '11-15'
    elif 15<x<=20:
        return '16-20'
    elif 20<x<=25:
        return '21-25'
    elif 25<x<=30:
        return '26-30'
    else:
        try:
            int(x) 
            return '31+'
        except:
            return x

def timeDelay(sec):
    time.sleep(sec)

#late or cancelled switcher
def formatting(x):
    if 'Late' in x:
        minutes=float(x.split('-')[1].strip().split()[0].strip())
        return minutes
    else:
        return x

#creating folder of different branchs
def pivot(filename, finaldir):
    table.columns=['date','branch','late']
    table['count']=0
    table.loc[:,'date']=table.date.apply(lambda x:x.split('/')[-1]+'-'+x.split('/')[0])
    table.loc[:,'mins']=table.late.apply(formatting)
    table=table.sort(columns=['branch','mins'])
    del table['late']
    table.loc[:,'mins']=table.mins.apply(range_switcher)
    new_table=table.groupby(by=['branch','date','mins'],sort=False).agg('count').reset_index()
    new_table['branch-late']=new_table['branch']+'   '+new_table['mins']
    del new_table['mins']
    if not os.path.exists(finaldir):
        os.makedirs(finaldir)
    pivot_table=df()
    for i in new_table.index:
        pivot_table.loc[new_table.ix[i,'date'],new_table.ix[i,'branch-late']]=new_table.ix[i,'count']
    pivot_table.to_csv(os.path.join(finaldir,'%s_Delayed_Canceled_Trains.csv'%(finaldir)))

In [57]:
filename='raw_data/LIRR.csv'
table=df.from_csv(filename,header=None,index_col=None)

In [58]:
table.columns=['date','branch','late']
table['count']=0
table.loc[:,'date']=table.date.apply(lambda x:x.split('/')[-1]+'-'+x.split('/')[0])
table.loc[:,'mins']=table.late.apply(formatting)
table=table.sort(columns=['branch','mins'])
del table['late']
table.loc[:,'mins']=table.mins.apply(range_switcher)

In [59]:
new_table=table.groupby(by=['branch','date','mins'],sort=False).agg('count').reset_index()
new_table['branch-late']=new_table['branch']+'   '+new_table['mins']
del new_table['mins']

In [60]:
pivot_table=df()
for i in new_table.index:
    pivot_table.loc[new_table.ix[i,'date'],new_table.ix[i,'branch-late']]=new_table.ix[i,'count']

In [51]:
pivot_table.to_csv(os.path.join(finaldir,'%s_Delayed_Canceled_Trains.csv'%(finaldir)))

In [54]:
table.columns=['date','branch','late']
table['count']=0
table.loc[:,'date']=table.date.apply(lambda x:x.split('/')[-1]+'-'+x.split('/')[0])
table.loc[:,'mins']=table.late.apply(formatting)
table=table.sort(columns=['branch','mins'])
del table['late']

In [61]:
pivot_table

,Babylon 6-10,Babylon 11-15,Babylon 16-20,Babylon 21-25,Babylon 26-30,Babylon 31+,Babylon Canceled,Babylon Partially Canceled,Far Rockaway 6-10,Far Rockaway 11-15,...,Ronk. (greenpt.) Canceled,Ronk. (greenpt.) Partially Canceled,West Hempstead 6-10,West Hempstead 11-15,West Hempstead 16-20,West Hempstead 21-25,West Hempstead 26-30,West Hempstead 31+,West Hempstead Canceled,West Hempstead Partially Canceled
2010-07,84,30,3,2,3,1,4,4,9,1,...,18,11,5,1,1,NaN,NaN,1,NaN,3
2010-08,293,110,40,25,6,16,60,2,64,29,...,22,3,7,8,3,NaN,2,NaN,78,1
2010-09,167,33,18,9,2,17,48,11,22,8,...,22,7,12,5,1,1,NaN,3,4,NaN
2010-10,195,44,20,10,3,4,8,8,31,14,...,5,2,5,3,NaN,NaN,NaN,1,NaN,2
2010-11,148,46,16,8,2,11,16,3,12,9,...,1,4,8,2,1,NaN,NaN,NaN,1,1
2010-12,176,50,27,14,6,13,27,6,42,5,...,18,15,17,2,3,NaN,NaN,2,5,NaN
2011-01,199,99,33,31,13,12,53,6,48,17,...,39,3,15,15,7,1,1,1,4,1
2011-02,100,32,9,3,3,9,14,4,21,11,...,1,2,10,2,NaN,NaN,NaN,NaN,NaN,NaN
2011-03,101,25,18,8,2,14,19,7,22,7,...,4,2,5,5,2,NaN,NaN,NaN,1,NaN
2011-04,74,30,10,3,NaN,3,5,10,19,10,...,NaN,6,7,3,1,1,NaN,NaN,1,3
2011-05,137,34,11,6,5,6,8,10,18,7,...,8,16,10,7,1,3,2,3,2,NaN
2011-06,99,44,10,10,2,21,11,4,37,16,...,4,6,14,4,1,NaN,NaN,NaN,1,1
2011-07,157,59,23,16,4,3,7,2,31,4,...,2,1,17,8,2,2,1,3,1,2
2011-08,164,63,17,18,13,48,94,9,28,14,...,11,7,12,3,4,1,2,2,NaN,1
2011-09,177,65,15,10,7,5,49,17,39,11,...,26,7,13,5,2,1,NaN,1,13,2
2011-10,131,38,8,4,1,1,7,7,32,7,...,9,8,11,3,NaN,NaN,NaN,NaN,NaN,1
2011-11,122,28,5,1,1,7,5,1,25,1,...,12,17,9,3,2,NaN,1,NaN,1,NaN
2011-12,94,35,14,10,4,2,12,1,21,3,...,2,5,11,3,1,NaN,NaN,NaN,NaN,1
2012-01,118,32,13,9,NaN,4,6,6,20,4,...,NaN,2,13,2,1,NaN,NaN,NaN,NaN,NaN
2012-02,71,19,11,1,2,17,17,11,16,6,...,2,6,12,1,2,NaN,NaN,NaN,NaN,NaN
2012-03,91,34,12,3,6,5,2,2,32,9,...,8,2,14,5,NaN,NaN,NaN,NaN,NaN,1
2012-04,99,32,10,7,2,9,14,3,21,3,...,27,12,5,4,NaN,2,NaN,NaN,2,1
2012-05,119,45,6,4,7,10,10,7,18,4,...,4,4,8,2,4,NaN,1,1,NaN,NaN
2012-06,155,48,25,4,8,15,22,5,22,21,...,13,19,16,6,NaN,NaN,NaN,1,NaN,NaN
2012-07,170,51,18,8,1,6,3,4,38,9,...,7,16,18,3,NaN,NaN,NaN,NaN,NaN,NaN
2012-08,172,61,13,6,4,4,8,5,48,9,...,1,2,16,9,4,NaN,1,NaN,NaN,2
2012-09,110,38,15,9,5,NaN,5,4,15,3,...,6,NaN,12,2,NaN,2,NaN,NaN,NaN,NaN
2012-10,112,26,5,3,4,11,24,6,22,3,...,5,NaN,16,5,2,1,1,NaN,NaN,NaN
2012-11,191,69,35,20,4,13,33,18,56,18,...,12,12,27,19,12,6,2,NaN,5,NaN
2012-12,179,47,17,2,4,6,9,3,50,10,...,5,5,26,3,2,NaN,NaN,NaN,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013-04,113,18,5,4,1,1,3,NaN,30,8,...,4,8,15,2,NaN,4,2,NaN,NaN,2
2013-05,164,35,18,6,3,9,13,5,50,12,...,8,10,20,5,NaN,NaN,NaN,NaN,NaN,1
2013-06,133,34,12,3,NaN,1,36,15,22,9,...,17,9,10,4,NaN,NaN,1,1,NaN,2
2013-07,197,50,12,5,5,NaN,15,11,41,10,...,4,9,29,3,4,NaN,NaN,NaN,NaN,NaN
2013-08,185,55,21,17,15,31,20,14,27,12,...,16,9,23,3,NaN,2,1,3,2,3
2013-09,141,54,20,9,5,2,9,7,31,7,...,7,4,28,2,3,NaN,NaN,NaN,NaN,NaN
2013-10,158,42,19,8,6,3,8,2,22,4,...,1,6,18,5,4,NaN,NaN,NaN,NaN,NaN
2013-11,258,63,10,7,1,NaN,5,10,45,11,...,6,NaN,28,3,3,1,1,NaN,NaN,2
2013-12,194,47,18,9,1,13,9,4,42,15,...,3,2,27,4,1,1,NaN,NaN,1,1
2014-01,314,103,42,17,10,15,47,32,76,23,...,15,28,35,8,3,1,1,1,1,NaN
2014-02,203,56,16,7,5,5,12,2,51,16,...,21,5,22,1,1,NaN,NaN,NaN,NaN,NaN
2014-03,202,55,15,7,3,4,9,2,40,6,...,2,1,23,5,NaN,1,NaN,3,NaN,NaN
2014-04,165,46,20,5,1,1,18,9,39,19,...,8,2,18,3,1,1,1,NaN,NaN,2
2014-05,215,68,30,10,7,12,20,4,54,8,...,4,4,30,3,1,2,NaN,1,1,NaN
2014-06,176,44,22,8,3,11,30,3,53,9,...,2,2,27,2,NaN,1,2,1,NaN,NaN
2014-07,166,46,21,15,5,17,16,2,26,14,...,2,NaN,21,3,2,NaN,1,1,NaN,NaN
2014-08,174,57,21,9,2,5,19,1,43,15,...,3,7,18,2,5,NaN,1,1,1,NaN
2014-09,158,47,24,8,5,18,17,8,49,13,...,1,3,21,5,2,1,1,1,2,1
2014-10,203,54,18,5,3,2,16,6,42,15,...,22,12,29,3,2,1,NaN,NaN,1,3
2014-11,197,57,18,9,8,12,4,12,45,10,...,16,3,24,7,1,1,NaN,NaN,NaN,1
2014-12,249,80,18,12,6,11,9,9,61,14,...,5,4,47,10,3,1,3,NaN,4,3
2015-01,174,57,41,26,14,12,42,12,46,22,...,24,11,21,6,5,NaN,1,NaN,12,3
2015-02,206,88,45,37,16,35,42,9,64,19,...,30,8,31,9,5,7,NaN,2,NaN,NaN
2015-03,225,74,21,13,7,13,14,8,62,12,...,13,10,21,7,3,1,NaN,1,2,2
2015-04,159,32,10,6,1,4,25,11,24,4,...,11,3,14,4,2,1,1,NaN,2,1
2015-05,189,47,14,4,3,3,18,6,42,5,...,3,8,30,3,NaN,1,NaN,NaN,NaN,2
2015-06,182,35,23,7,8,5,15,9,56,17,...,8,6,29,4,4,3,1,4,NaN,NaN
2015-07,219,48,22,7,3,9,18,1,49,14,...,6,5,22,8,2,1,NaN,NaN,7,NaN
2015-08,194,68,19,10,4,6,10,4,40,11,...,8,28,26,4,4,NaN,1,1,NaN,NaN
2015-09,24,5,7,2,1,13,21,10,4,1,...,6,8,4,2,NaN,NaN,NaN,1,NaN,1